# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-01 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20171127_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_pdf',
            field=models.FileField(default='', upload_to='songs/%Y/%m/%d'),
        ),
    ]
