# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-04 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_song_song_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_path',
        ),
    ]
